<?xml version="1.0"?>
<package format="3">
  <name>nurse_call</name>
  <version>0.0.1</version>
  <description>Mock call nurse action server/client (ROS2).</description>
  <maintainer email="val@todo.todo">val</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>interfaces</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
